import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile}from'node:fs/promises';
import {createFixture,ids}from'../homework/fixture.mjs';
const c='4e0b25e4-ec47-4745-8b2b-ba91c1504254',c2='40000000-0000-0000-0000-000000000002';
const migration=await readFile(new URL('../../database/upgrade/08-FEAT-004-MULTI-CLASS-CATALOG.sql',import.meta.url),'utf8');
async function setup(map=true){const db=await createFixture();await db.exec(`alter table classes add column code text default '7A9';alter table classes add column name text default '7A9';`);
 if(map)await db.exec(`alter table profiles drop constraint profiles_class_id_fkey;update classes set id='${c}';update profiles set class_id='${c}'where class_id='${ids.c}';update class_teachers set class_id='${c}';alter table profiles add foreign key(class_id)references classes(id);`);
 for(const f of ['05-FEAT-001-BAO-BAI.sql','06-FEAT-001-AI-RECOVERY.sql','07-FEAT-002-PERMISSIONS-LIFECYCLE.sql'])await db.exec(await readFile(new URL('../../database/upgrade/'+f,import.meta.url),'utf8'));return db;}
async function rpc(db,u,act,p={},cl=c){await db.exec(`set role authenticated;set request.jwt.claim.sub='${u}';`);try{return(await db.query('select public.homework_api($1,$2::jsonb) r',[act,JSON.stringify({class_id:cl,...p})])).rows[0].r;}finally{await db.exec('reset role');}}
test('unknown inventory aborts before mutation',async()=>{const db=await setup(false);try{await db.exec(`insert into classes(id,school_year_id,active)values('${c}','${ids.y}',true)`);await assert.rejects(db.exec(migration),/explicit grade mapping required/);await db.exec('rollback');assert.equal((await db.query("select count(*)::int n from information_schema.columns where table_name='classes'and column_name='grade'")).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from classes')).rows[0].n,2);}finally{await db.close();}});
test('explicit mapping preserves subjects; grade mandatory/immutable/range, never inferred',async()=>{const db=await setup();try{const sub=await rpc(db,ids.t,'subject_save',{name:'Toán',icon:'🧮'});await db.exec(`update classes set code='NOT-A-GRADE',name='Khác'`);const before=(await db.query('select id,name from class_subjects')).rows;await db.exec(migration);assert.deepEqual((await db.query('select id,name from class_subjects')).rows,before);assert.equal((await db.query('select grade from classes')).rows[0].grade,7);assert.ok((await db.query('select catalog_subject_id from class_subjects where id=$1',[sub.id])).rows[0].catalog_subject_id);await assert.rejects(db.exec(`insert into classes(id,school_year_id,active)values('${c2}','${ids.y}',true)`),/null value/);await assert.rejects(db.exec('update classes set grade=8'),/flow riêng/);await assert.rejects(db.exec(`insert into classes(id,school_year_id,active,grade)values('${c2}','${ids.y}',true,5)`),/classes_grade_v1/);await db.exec(`insert into classes(id,school_year_id,active,grade,code)values('${c2}','${ids.y}',true,8,'7Z')`);}finally{await db.close();}});
test('permissions, forged class/grade, catalog lifecycle and no old dispatcher bypass',async()=>{const db=await setup();try{await db.exec(migration);await db.exec(`insert into classes(id,school_year_id,active,grade)values('${c2}','${ids.y}',true,8)`);const cat=await rpc(db,ids.a,'catalog_save',{grade:7,name:'Toán'},'');const cat8=await rpc(db,ids.a,'catalog_save',{grade:8,name:'Toán'},'');
 for(const u of[ids.t,ids.m,ids.s]){await assert.rejects(rpc(db,u,'subject_save',{catalog_subject_id:cat8.id},c2));await assert.rejects(rpc(db,u,'group_save',{name:'Forged'},c2));await assert.rejects(rpc(db,u,'submit',{subject_id:cat8.id,request_id:crypto.randomUUID()},c2));await assert.rejects(rpc(db,u,'catalog_save',{grade:7,name:'X'},''),/Chỉ Admin/);await assert.rejects(rpc(db,u,'load',{},c2));}
 await assert.rejects(rpc(db,ids.t,'subject_save',{catalog_subject_id:cat8.id}),/khối lớp/);await assert.rejects(rpc(db,ids.t,'subject_save',{catalog_subject_id:cat.id,name:'forged'}),/Chỉ sửa/);
 for(const u of[ids.a,ids.m,ids.s])await assert.rejects(rpc(db,u,'subject_save',{catalog_subject_id:cat.id}),/Chỉ Teacher/);
 const cs=await rpc(db,ids.t,'subject_save',{catalog_subject_id:cat.id});await rpc(db,ids.a,'catalog_save',{id:cat.id,grade:7,name:'Toán',is_active:false},'');await rpc(db,ids.t,'subject_save',{id:cs.id,catalog_subject_id:cat.id,is_active:false});await assert.rejects(rpc(db,ids.t,'subject_save',{id:cs.id,catalog_subject_id:cat.id,is_active:true}),/ngừng hoạt động/);assert.equal((await rpc(db,ids.t,'load')).catalog.length,0);await assert.rejects(rpc(db,ids.a,'oversight',{grade:7},c2),/Khối/);
 await db.exec(`set role authenticated;set request.jwt.claim.sub='${ids.t}';`);for(const sql of['select *from grade_subject_catalog','update class_subjects set is_active=true',"select homework_private.api_v3('subject_save','{}')"])await assert.rejects(db.exec(sql),/permission denied/);await db.exec('reset role');assert.equal((await rpc(db,ids.t,'context',{},'')).classes.length,1);await db.exec('update class_teachers set active=false');assert.equal((await rpc(db,ids.t,'context',{},'')).classes.length,0);await assert.rejects(rpc(db,ids.t,'load'));}finally{await db.close();}});
async function server(db,action,p){await db.exec('set role service_role');try{return(await db.query('select homework_ai($1,$2::jsonb)r',[action,JSON.stringify(p)])).rows[0].r;}finally{await db.exec('reset role');}}
async function publish(db,subject,who=ids.s,cl=c,title='Bài mới'){const n=await rpc(db,who,'submit',{subject_id:subject,title,content:'Nội dung '+title,due_at:'2026-10-05T12:00:00Z',request_id:crypto.randomUUID()},cl);const snap=await server(db,'snapshot',{id:n.id});await server(db,'finish',{id:n.id,revision:snap.notice.revision,fingerprint:snap.fingerprint,score:0,candidate_id:null,reason:'ok'});return n;}
test('migration preserves populated class/profile/notices/reactions/audit/membership and rejects ambiguous catalogs atomically',async()=>{const db=await setup();try{const s=await rpc(db,ids.t,'subject_save',{name:'Toán'});const n=await publish(db,s.id);await rpc(db,ids.other,'heart',{id:n.id,liked:true});const group=await rpc(db,ids.t,'group_save',{name:'E1'});await rpc(db,ids.t,'group_assign',{student_id:ids.s,english_group_id:group.id});
 const tables=['classes','profiles','class_teachers','homework_notices','homework_notice_reactions','homework_contribution_events','english_groups','english_group_members'];const before={};for(const t of tables)before[t]=(await db.query(`select to_jsonb(x)r from public.${t} x order by to_jsonb(x)::text`)).rows;
 await db.exec(migration);for(const t of tables){const after=(await db.query(`select ${t==='classes'?"to_jsonb(x)-'grade'":"to_jsonb(x)"} r from public.${t} x order by ${t==='classes'?"(to_jsonb(x)-'grade')::text":"to_jsonb(x)::text"}`)).rows;assert.deepEqual(after,before[t],t);}
 assert.equal((await rpc(db,ids.s,'load')).notices.length,1);
 }finally{await db.close();}
 const amb=await setup();try{await rpc(amb,ids.t,'subject_save',{name:'Toán',icon:'A'});await rpc(amb,ids.t,'subject_save',{name:'TOÁN',icon:'B'});await assert.rejects(amb.exec(migration),/ambiguous subject mapping/);await amb.exec('rollback');assert.equal((await amb.query('select count(*)::int n from class_subjects')).rows[0].n,2);assert.equal((await amb.query("select to_regclass('grade_subject_catalog') r")).rows[0].r,null);}finally{await amb.close();}});
test('multi-class oversight filters, per-class rankings, tombstone redaction and unchanged hard delete',async()=>{const db=await setup();try{const math=await rpc(db,ids.t,'subject_save',{name:'Toán'});const n=await publish(db,math.id);await rpc(db,ids.other,'heart',{id:n.id,liked:true});await db.exec(migration);
 await db.exec(`insert into classes(id,school_year_id,active,grade,code,name)values('${c2}','${ids.y}',true,8,'8A1','Lớp 8');insert into class_teachers values('${c2}','${ids.t}',true);`);
 assert.equal((await rpc(db,ids.t,'context',{},'')).classes.length,2);
 const cat=await rpc(db,ids.a,'catalog_save',{grade:8,name:'KHTN'},'');const sub=await rpc(db,ids.t,'subject_save',{catalog_subject_id:cat.id},c2);await publish(db,sub.id,ids.t,c2,'Lớp tám');
 const all=await rpc(db,ids.a,'oversight',{},'');assert.equal(all.metrics.published,2);assert.equal(all.hearts,1);assert.equal(all.metrics.contributors,1);
 const only=await rpc(db,ids.a,'oversight',{grade:7},'');assert.equal(only.metrics.published,1);assert.ok(only.history.every(x=>x.class_id===c));assert.ok(only.audit.every(x=>x.class_id===c));
 assert.equal((await rpc(db,ids.a,'oversight',{actor_id:ids.t},c)).history.length,0);assert.equal((await rpc(db,ids.a,'oversight',{from:'2099-01-01'},c)).history.length,0);
 const teacherData=await rpc(db,ids.t,'load');assert.equal(teacherData.history.length,1);assert.ok(teacherData.history.every(n=>n.class_id===c));const teacherAwards=teacherData.leaderboard;assert.deepEqual((await rpc(db,ids.a,'load')).leaderboard,teacherAwards);
 for(const u of[ids.s,ids.m])for(const action of['load','oversight','context']){if(action==='context'){assert.deepEqual((await rpc(db,u,action,{},'')).classes.map(x=>x.id),[c]);}else await assert.rejects(rpc(db,u,action,{},c2));}
 for(const action of['submit','delete','restore','remind','review','group_assign','group_save','ai_settings'])await assert.rejects(rpc(db,ids.a,action,{id:n.id}),{code:'42501'});
 await rpc(db,ids.s,'delete',{id:n.id,reason:'Sai bài'});assert.equal((await rpc(db,ids.a,'oversight',{},c)).trash.length,1);assert.equal((await rpc(db,ids.a,'oversight',{},c2)).trash.length,0);
 await rpc(db,ids.a,'hard_delete',{id:n.id,hard_delete_reason:'Test purge',confirm_irreversible:true});const redacted=await rpc(db,ids.a,'oversight',{status:'hard_deleted'},c);assert.equal(redacted.history.length,1);assert.equal(redacted.history[0].title,undefined);assert.equal(redacted.history[0].content,undefined);assert.equal(redacted.history[0].due_at,undefined);assert.ok(redacted.history[0].marker);
 const audit=await rpc(db,ids.a,'oversight',{event_type:'hard_delete',actor_id:ids.a},c);assert.ok(audit.audit.length>0);assert.ok(audit.audit.every(e=>e.actor_id===ids.a&&e.event_type==='hard_delete'));assert.ok(!JSON.stringify(audit).includes('Nội dung Bài mới'));
 await db.exec(`update classes set active=false where id='${c2}'`);await assert.rejects(rpc(db,ids.t,'load',{},c2));assert.equal((await rpc(db,ids.t,'context',{},'')).classes.length,1);assert.equal((await rpc(db,ids.a,'oversight',{},c2)).metrics.published,1);
 }finally{await db.close();}});
test('catalog canonical metadata, inactive historical notices and English group visibility survive migration',async()=>{const db=await setup();try{const eng=await rpc(db,ids.t,'subject_save',{name:'English',is_english:true});const g1=await rpc(db,ids.t,'group_save',{name:'E1'}),g2=await rpc(db,ids.t,'group_save',{name:'E2'});await rpc(db,ids.t,'group_assign',{student_id:ids.s,english_group_id:g1.id});await rpc(db,ids.t,'group_assign',{student_id:ids.other,english_group_id:g2.id});await db.exec(migration);
 const subject=(await rpc(db,ids.t,'load')).subjects.find(x=>x.id===eng.id);
 const n=await rpc(db,ids.s,'submit',{subject_id:eng.id,english_group_id:g1.id,title:'E1 work',content:'Reading',due_at:'2026-10-10T12:00:00Z',request_id:crypto.randomUUID()});const snap=await server(db,'snapshot',{id:n.id});await server(db,'finish',{id:n.id,revision:snap.notice.revision,fingerprint:snap.fingerprint,score:0,candidate_id:null});assert.equal((await rpc(db,ids.other,'load')).notices.length,0);assert.equal((await rpc(db,ids.s,'load')).notices.length,1);
 await assert.rejects(rpc(db,ids.a,'catalog_save',{id:subject.catalog_subject_id,grade:7,name:'English',is_english:false},''),/lịch sử/);
 await rpc(db,ids.a,'catalog_save',{id:subject.catalog_subject_id,grade:7,name:'Tiếng Anh',icon:'🔤',is_active:false},'');assert.equal((await rpc(db,ids.s,'load')).notices[0].subject,'Tiếng Anh');await rpc(db,ids.t,'subject_save',{id:eng.id,catalog_subject_id:subject.catalog_subject_id,is_active:false});assert.equal((await rpc(db,ids.s,'load')).history.length,1);
 await assert.rejects(rpc(db,ids.s,'submit',{subject_id:eng.id,english_group_id:g1.id,title:'New',content:'No',due_at:'2026-10-10T12:00:00Z',request_id:crypto.randomUUID()}));
 }finally{await db.close();}});
