import {beforeEach,afterEach,it,expect,vi}from'vitest';
import {reactive}from'vue';import{createPinia,setActivePinia}from'pinia';
import{mount,settle,findAll,textOf,click}from'../bug-001/renderer';
const env=vi.hoisted(()=>({auth:null as any,ctx:null as any,rpc:vi.fn()}));
vi.mock('../../src/stores/auth',()=>({useAuthStore:()=>env.auth}));
vi.mock('../../src/stores/context',()=>({useContextStore:()=>env.ctx}));
vi.mock('../../src/services/legacy-supabase',()=>({legacyApi:{teacherListUsers:async()=>({users:[]})}}));
vi.mock('../../src/features/homework/api',async original=>({...await original<any>(),homeworkRpc:env.rpc}));
vi.mock('vue-router',()=>({useRouter:()=>({push:vi.fn()})}));
import Inbox from '../../src/components/homework/HomeworkInbox.vue';
import Page from'../../src/pages/HomeworkPage.vue';import{useHomeworkViewStore}from'../../src/features/homework/view-context';
const context={grades:[6,7,8,9,10,11,12],classes:[{id:'a',code:'7A',grade:7,active:true,school_year_id:'y'},{id:'b',code:'8B',grade:8,active:true,school_year_id:'y2'}]};
const data=(c:string)=>({settings:{seed_threshold:3},catalog:[{id:'cat'+c,grade:c==='a'?7:8,name:'Catalog '+c,is_active:true}],subjects:[],groups:[],members:[],learners:[],notices:[{id:c,title:'Notice '+c,author_id:'s',author_role:'student',author_name:'S',class_id:c,subject:'Toán',status:'published',due_at:'2099-01-01T00:00:00Z',created_at:'2026-09-01T00:00:00Z'}],history:[],queue:[],review_history:[],audit:[],trash:[],leaderboard:[],notifications:[],ai_settings:{semantic_duplicate_enabled:true,duplicate_review_threshold:70,duplicate_auto_threshold:90}});
const oversight=(c:string)=>({metrics:{published:c==='a'?7:c==='b'?8:15},hearts:0,people:[],history:[],audit:[],catalog_audit:[],trash:[]});
const response=(action:string,c:string)=>action==='context'?context:action==='load'?data(c):action==='catalog_list'?[]:action==='oversight'?oversight(c):{ok:true};
let app:any,root:any;
beforeEach(()=>{setActivePinia(createPinia());env.auth=reactive({role:'teacher',currentUser:{id:'t',classId:null}});env.ctx=reactive({selectedClassId:'a',selectedWeekId:null,weeks:[],classes:[]});env.rpc.mockReset().mockImplementation(async(a:string,c:string)=>response(a,c));vi.stubGlobal('Document',class{});vi.stubGlobal('ShadowRoot',class{});vi.stubGlobal('document',{activeElement:null});});
afterEach(()=>{app?.unmount();vi.unstubAllGlobals();});
async function render(){const m=mount(Page);app=m.app;root=m.root;await settle();await settle();}
function labelControl(label:string,type='select'){const l=findAll(root,n=>n.type==='label'&&textOf(n).startsWith(label))[0];expect(l).toBeDefined();const f=findAll(l,n=>n.type===type)[0];expect(f).toBeDefined();return f;}
async function change(label:string,value:any,type='select'){labelControl(label,type).props['onUpdate:modelValue'](value);await settle();await settle();}
it('Teacher switches assigned classes, clears editor/state and inbox scope; stale response cannot replace current class',async()=>{await render();expect(textOf(root)).toContain('Notice a');const compose=findAll(root,n=>n.props.class==='composer-launch')[0];await compose.props.onClick();await settle();expect(textOf(root)).toContain('✏️ Đăng Báo bài');let resolve!:(v:any)=>void;env.rpc.mockImplementation((act,c)=>act==='load'&&c==='b'?new Promise(r=>resolve=r):Promise.resolve(response(act,c)));await change('Lớp đang thao tác','b');expect(textOf(root)).not.toContain('Notice a');expect(findAll(root,n=>n.props.role==='dialog')).toHaveLength(0);await change('Lớp đang thao tác','a');resolve(data('b'));await settle();expect(textOf(root)).toContain('Notice a');expect(textOf(root)).not.toContain('Notice b');expect(useHomeworkViewStore().scopeClassId).toBe('a');});
it('Teacher with no assignment has no fallback class operation',async()=>{env.rpc.mockImplementation(async a=>a==='context'?{...context,classes:[]}:{});await render();expect(textOf(root)).toContain('Chưa có lớp');expect(env.rpc.mock.calls.some(c=>c[0]==='load')).toBe(false);});
it('Teacher subject form sends only catalog reference and local metadata',async()=>{await render();await click(root,'Môn học');expect(textOf(root)).toContain('Catalog a');expect(textOf(root)).not.toContain('Tên ngắn');await change('Môn trong danh mục khối','cata');const form=findAll(root,n=>n.type==='form')[0];await form.props.onSubmit({preventDefault(){}});await settle();expect(env.rpc).toHaveBeenCalledWith('subject_save','a',{id:null,catalog_subject_id:'cata',sort_order:0,is_active:true});});
it('Admin overview has catalog/oversight only, resets class on grade change and drops stale results',async()=>{env.auth.role='admin';await render();expect(textOf(root)).toContain('Giám sát học tập');expect(findAll(root,n=>n.type==='button').map(textOf).join('|')).not.toMatch(/Bảng Báo bài|Cài đặt AI|AI trùng/);await change('Lớp','a');expect(useHomeworkViewStore().scopeClassId).toBe('a');let resolve!:(v:any)=>void;env.rpc.mockImplementation((act,c)=>act==='oversight'&&c==='b'?new Promise(r=>resolve=r):Promise.resolve(response(act,c)));await change('Lớp','b');await change('Khối',7);resolve(oversight('b'));await settle();expect(useHomeworkViewStore().scopeClassId).toBe('');expect(env.rpc).toHaveBeenCalledWith('oversight','',expect.objectContaining({grade:7}));expect(findAll(root,n=>n.type==='option').map(textOf)).not.toContain('8B · Khối 8');expect(findAll(root,n=>n.type==='strong').map(textOf)).not.toContain('8');});
it('Admin history filters pass author/status/date scope; awards require one class',async()=>{env.auth.role='admin';await render();await click(root,'Lịch sử đăng');await change('Trạng thái','hard_deleted');await change('Từ ngày','2026-09-01','input');expect(env.rpc).toHaveBeenCalledWith('oversight','',expect.objectContaining({status:'hard_deleted',from:'2026-09-01T00:00:00+07:00'}));await click(root,'🌟 Góc tuyên dương');expect(textOf(root)).toContain('Chọn một lớp');expect(env.rpc.mock.calls.filter(c=>c[0]==='load')).toHaveLength(0);});
it('Admin catalog payload includes explicit grade and exposes save failure without false success',async()=>{env.auth.role='admin';await render();await click(root,'Danh mục môn');await change('Tên môn','Công nghệ','input');env.rpc.mockImplementation(async(a,c)=>{if(a==='catalog_save')throw Error('Catalog conflict');return response(a,c)});await findAll(root,n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});await settle();expect(textOf(root)).toContain('Catalog conflict');expect(textOf(root)).not.toContain('Đã lưu thay đổi');expect(env.rpc).toHaveBeenCalledWith('catalog_save','',expect.objectContaining({grade:7,name:'Công nghệ'}));});

it('Inbox follows the explicit homework class and clears old items on scope changes',async()=>{
 const view=useHomeworkViewStore();view.scopeClassId='b';env.rpc.mockImplementation(async(action,c)=>action==='inbox'?[{id:c,title:'Inbox '+c,message:'M',is_read:false,created_at:'2026-09-01T00:00:00Z'}]:{});
 const m=mount(Inbox);app=m.app;root=m.root;await settle();expect(env.rpc).toHaveBeenCalledWith('inbox','b');view.scopeClassId='';await settle();expect(textOf(root)).not.toContain('Inbox b');expect(env.rpc.mock.calls.filter(c=>c[0]==='inbox')).toHaveLength(1);
});
