<script setup lang="ts">
import { computed, type Component } from 'vue'
import { useRoute } from 'vue-router'
import { CalendarClock, CalendarRange, ChartNoAxesCombined, ClipboardCheck, GraduationCap, History, LayoutDashboard, MessagesSquare, NotebookPen, Settings, ShieldCheck, TriangleAlert, UsersRound } from 'lucide-vue-next'
import { useAuthStore } from '../../stores/auth'
import { visibleNavigation } from '../../features/navigation/navigation'
const props=defineProps<{collapsed:boolean}>();const route=useRoute();const auth=useAuthStore()
const icons:Record<string,Component>={LayoutDashboard,NotebookPen,ClipboardCheck,UsersRound,CalendarRange,CalendarClock,GraduationCap,ChartNoAxesCombined,History,MessagesSquare,ShieldCheck,TriangleAlert,Settings}
const items=computed(()=>visibleNavigation(auth.currentUser?.role))
</script>
<template><nav class="side-nav" aria-label="Điều hướng chính"><RouterLink v-for="item in items" :key="item.to" :to="item.to" class="nav-item" :class="{active:route.path===item.to}" :title="collapsed?item.label:undefined"><component :is="icons[item.icon]"/><span v-if="!collapsed">{{ item.label }}</span></RouterLink></nav></template>
<style scoped>
.side-nav{display:grid;gap:6px;padding:10px 8px}.nav-item{--nav-accent:var(--color-primary);position:relative;isolation:isolate;overflow:hidden;min-height:46px;display:flex;align-items:center;gap:12px;padding:9px 12px;border:1px solid transparent;border-radius:14px;color:var(--text-muted);font-weight:750;transition:background var(--transition-fast),color var(--transition-fast),transform var(--transition-fast),border-color var(--transition-fast),box-shadow var(--transition-fast)}.nav-item::before{content:"";position:absolute;z-index:-1;inset:0;background:linear-gradient(110deg,transparent 18%,color-mix(in srgb,var(--nav-accent) 12%,transparent) 50%,transparent 82%);transform:translateX(-115%);transition:transform .38s var(--ease-out)}
.nav-item:nth-child(2){--nav-accent:var(--color-sky)}.nav-item:nth-child(3){--nav-accent:var(--color-mint)}.nav-item:nth-child(4){--nav-accent:var(--color-coral)}.nav-item:nth-child(5){--nav-accent:var(--color-sun)}.nav-item:nth-child(6){--nav-accent:var(--color-pink)}.nav-item:nth-child(7){--nav-accent:var(--color-lilac)}.nav-item:nth-child(8){--nav-accent:var(--color-info)}
.nav-item:hover{background:color-mix(in srgb,var(--nav-accent) 10%,var(--surface));border-color:color-mix(in srgb,var(--nav-accent) 22%,var(--border));color:var(--nav-accent);transform:translateX(4px) scale(1.01);box-shadow:0 8px 20px color-mix(in srgb,var(--nav-accent) 10%,transparent)}.nav-item:hover::before{transform:translateX(115%)}.nav-item.active{background:linear-gradient(105deg,color-mix(in srgb,var(--nav-accent) 17%,var(--surface)),color-mix(in srgb,var(--nav-accent) 6%,var(--surface)));border-color:color-mix(in srgb,var(--nav-accent) 18%,var(--border));color:var(--nav-accent);box-shadow:inset 4px 0 0 var(--nav-accent),0 5px 14px color-mix(in srgb,var(--nav-accent) 10%,transparent)}.nav-item :deep(svg){width:20px;height:20px;flex:0 0 20px;stroke:currentColor;transition:transform var(--transition-fast),filter var(--transition-fast)}.nav-item:hover :deep(svg){transform:translateX(1px) scale(1.12);filter:drop-shadow(0 4px 7px color-mix(in srgb,var(--nav-accent) 28%,transparent))}.nav-item.active :deep(svg){transform:scale(1.08)}
</style>
