<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Building2, CalendarDays, GraduationCap, Plus, RefreshCw, ShieldCheck, UserCog } from 'lucide-vue-next'
import { useQueryClient } from '@tanstack/vue-query'
import { useRoute } from 'vue-router'
import AppButton from '../components/ui/AppButton.vue'
import AppCard from '../components/ui/AppCard.vue'
import InlineStatus, { type InlineStatusState } from '../components/ui/InlineStatus.vue'
import AdminClassCard from '../components/admin/AdminClassCard.vue'
import AdminTeacherCard from '../components/admin/AdminTeacherCard.vue'
import AdminStudentCard from '../components/admin/AdminStudentCard.vue'
import AdminSchoolYearCard from '../components/admin/AdminSchoolYearCard.vue'
import AdminAuditLog from '../components/admin/AdminAuditLog.vue'
import PermissionMatrix from '../components/admin/PermissionMatrix.vue'
import { assignTeacher, createClass, createManagedUser, createSchoolYear, createTeacher, deleteClass, hardDeleteUser, resetManagedPassword, setActiveSchoolYear, updateClass, updateManagedUser, updateSchoolYearPeriods, updateSchoolYearWeek, updateTeacher, useAdminDirectory, type AdminMutationRuntime } from '../features/admin/admin-directory'
import { useAuthStore } from '../stores/auth'
import { useContextStore } from '../stores/context'
import type { DirectoryUser } from '../types/legacy'

const auth=useAuthStore(),context=useContextStore(),queryClient=useQueryClient(),route=useRoute(),directory=useAdminDirectory()
const validTabs=['overview','years','classes','students','teachers','permissions','audit']
const tab=computed(()=>{const value=String(route.query.tab??'overview');return validTabs.includes(value)?value:'overview'})
const busyKey=ref<string|null>(null),status=ref<InlineStatusState>('idle'),statusMessage=ref(''),showYearForm=ref(false),showClassForm=ref(false),showTeacherForm=ref(false),showStudentForm=ref(false)
const yearForm=reactive({name:'',startDate:'',endDate:'',setActive:true}),classForm=reactive({code:'',name:''}),teacherForm=reactive({code:'',fullName:'',password:''}),studentForm=reactive({code:'',fullName:'',password:'',role:'student' as 'student'|'monitor',classId:''})
const studentSearch=ref(''),studentYearFilter=ref(''),studentClassFilter=ref(''),studentRoleFilter=ref(''),studentStatusFilter=ref('')

const data=computed(()=>directory.data.value??{schoolYears:[],weeks:[],periods:[],classes:[],teachers:[],assignments:[],users:[]})
const mergedSchoolYears=computed(()=>{const schoolYearsById=new Map(context.schoolYears.map(item=>[item.id,{...item}]));for(const item of data.value.schoolYears)schoolYearsById.set(item.id,{...(schoolYearsById.get(item.id)??{}),...item});return [...schoolYearsById.values()].sort((a,b)=>String(b.startDate).localeCompare(String(a.startDate)))})
const schoolYearCount=computed(()=>mergedSchoolYears.value.length)
const selectedYearId=computed(()=>context.selectedSchoolYearId||auth.legacyState?.selectedSchoolYearId||auth.legacyState?.activeSchoolYearId||null)
const selectedYear=computed(()=>mergedSchoolYears.value.find(item=>item.id===selectedYearId.value)??mergedSchoolYears.value.find(item=>item.active)??null)
const yearClasses=computed(()=>data.value.classes.filter(item=>!selectedYear.value||item.schoolYearId===selectedYear.value.id))
const activeClasses=computed(()=>yearClasses.value.filter(item=>item.active)),activeTeachers=computed(()=>data.value.teachers.filter(item=>item.active)),activeAssignments=computed(()=>data.value.assignments.filter(item=>item.active&&activeClasses.value.some(cls=>cls.id===item.classId)))
const learners=computed(()=>data.value.users.filter(item=>item.role==='student'||item.role==='monitor'))
const activeLearners=computed(()=>learners.value.filter(item=>item.active))
const classById=computed(()=>new Map(data.value.classes.map(item=>[item.id,item])))
const filteredLearners=computed(()=>{const q=studentSearch.value.trim().toLowerCase();return learners.value.filter(user=>{const cls=user.classId?classById.value.get(user.classId):null;if(studentYearFilter.value&&cls?.schoolYearId!==studentYearFilter.value)return false;if(studentClassFilter.value&&user.classId!==studentClassFilter.value)return false;if(studentRoleFilter.value&&user.role!==studentRoleFilter.value)return false;if(studentStatusFilter.value==='active'&&!user.active)return false;if(studentStatusFilter.value==='inactive'&&user.active)return false;if(q&&![user.code,user.fullName,cls?.code].some(value=>String(value??'').toLowerCase().includes(q)))return false;return true})})
function assignedTeachers(classId:string){return data.value.teachers.filter(teacher=>data.value.assignments.some(row=>row.classId===classId&&row.teacherId===teacher.id&&row.active))}
function assignedClasses(teacherId:string){return data.value.classes.filter(item=>data.value.assignments.some(row=>row.classId===item.id&&row.teacherId===teacherId&&row.active))}
function runtime():AdminMutationRuntime{return{queryClient,reload:async()=>{await auth.reload(context.selectedClassId,context.selectedSchoolYearId);context.hydrate(auth.legacyState);return auth.legacyState}}}
async function run(key:string,task:()=>Promise<unknown>,message:string){busyKey.value=key;try{await task();status.value='success';statusMessage.value=message}catch(error){status.value='error';statusMessage.value=error instanceof Error?error.message:'Không thực hiện được thao tác quản trị.'}finally{busyKey.value=null}}
async function submitYear(){const name=yearForm.name.trim();if(!name||!yearForm.startDate||!yearForm.endDate)return;if(yearForm.endDate<yearForm.startDate){status.value='error';statusMessage.value='Ngày kết thúc năm học phải sau ngày bắt đầu tuần 1.';return}let createdId='';await run('create-year',async()=>{const result=await createSchoolYear(runtime(),{name,startDate:yearForm.startDate,endDate:yearForm.endDate,setActive:yearForm.setActive});createdId=String((result as {schoolYearId?:unknown})?.schoolYearId??'')},'Đã tạo năm học và các tuần cơ sở.');if(createdId&&yearForm.setActive){context.selectSchoolYear(createdId);await auth.reload(null,createdId);context.hydrate(auth.legacyState)}if(status.value==='success'){yearForm.name='';yearForm.startDate='';yearForm.endDate='';yearForm.setActive=true;showYearForm.value=false}}
async function activateYear(id:string){if(!window.confirm('Đặt năm học này thành năm học đang hoạt động?'))return;await run(`year:${id}`,()=>setActiveSchoolYear(runtime(),id),'Đã chuyển năm học đang hoạt động.');if(status.value==='success'){context.selectSchoolYear(id);await auth.reload(null,id);context.hydrate(auth.legacyState)}}
function yearWeeks(yearId:string){return data.value.weeks.filter(item=>item.schoolYearId===yearId).sort((a,b)=>a.number-b.number)}
function yearPeriods(yearId:string){return data.value.periods.filter(item=>item.schoolYearId===yearId).sort((a,b)=>a.number-b.number)}
async function saveYearWeek(input:{weekId:string;startDate:string;endDate:string}){await run(`week:${input.weekId}`,()=>updateSchoolYearWeek(runtime(),input),'Đã cập nhật lịch tuần chuẩn.')}
async function saveYearPeriods(input:{schoolYearId:string;periods:Array<{number:number;start:string;end:string}>}){await run(`periods:${input.schoolYearId}`,()=>updateSchoolYearPeriods(runtime(),input),'Đã cập nhật khung giờ tiết học của năm học.')}
async function submitClass(){const code=classForm.code.trim().toUpperCase(),name=classForm.name.trim();if(!code||!name||!selectedYearId.value)return;await run('create-class',()=>createClass(runtime(),{code,name,schoolYearId:selectedYearId.value}),'Đã tạo lớp.');classForm.code='';classForm.name='';showClassForm.value=false}
async function editClass(id:string){const item=data.value.classes.find(row=>row.id===id);if(!item)return;const code=window.prompt('Mã lớp:',item.code)?.trim().toUpperCase();if(!code)return;const name=window.prompt('Tên lớp:',item.name)?.trim();if(!name)return;await run(`class:${id}`,()=>updateClass(runtime(),id,{code,name}),'Đã cập nhật lớp.')}
async function toggleClass(id:string){const item=data.value.classes.find(row=>row.id===id);if(!item)return;if(item.active&&!window.confirm('Khóa lớp này? Backend chỉ cho phép khi trạng thái hợp lệ.'))return;await run(`class:${id}`,()=>updateClass(runtime(),id,{active:!item.active}),item.active?'Đã khóa lớp.':'Đã kích hoạt lớp.')}
async function removeClass(id:string){const item=data.value.classes.find(row=>row.id===id);if(!item?.canDelete||!window.confirm(`Xóa vĩnh viễn lớp rỗng ${item.code}?`))return;await run(`class:${id}`,()=>deleteClass(runtime(),id),'Đã xóa lớp rỗng.')}
async function submitStudent(){const code=studentForm.code.trim().toUpperCase(),fullName=studentForm.fullName.trim();if(!code||!fullName||!studentForm.classId)return;let result:unknown;await run('create-student',async()=>{result=await createManagedUser(runtime(),{code,fullName,role:studentForm.role,classId:studentForm.classId,active:true,password:studentForm.password})},'Đã tạo học sinh/cán sự.');const password=String((result as {password?:unknown}|undefined)?.password??'');if(password)statusMessage.value=`Đã tạo ${code}. Mật khẩu tạm: ${password}`;if(status.value==='success'){studentForm.code='';studentForm.fullName='';studentForm.password='';studentForm.role='student';showStudentForm.value=false}}
async function editStudent(user:DirectoryUser){const code=window.prompt('Mã đăng nhập:',user.code)?.trim().toUpperCase();if(!code)return;const fullName=window.prompt('Họ và tên:',user.fullName)?.trim();if(!fullName)return;const roleText=window.prompt('Vai trò: student hoặc monitor',user.role)?.trim();if(roleText!=='student'&&roleText!=='monitor')return;const currentClass=classById.value.get(user.classId||'');const classCode=window.prompt('Mã lớp:',currentClass?.code||'')?.trim().toUpperCase();const targetClass=data.value.classes.find(item=>item.code.toUpperCase()===classCode);if(!targetClass){status.value='error';statusMessage.value='Không tìm thấy lớp.';return}await run(`student:${user.id}`,()=>updateManagedUser(runtime(),user.id,{changeCode:code!==user.code,code,fullName,role:roleText,classId:targetClass.id,active:user.active}),'Đã cập nhật học sinh/cán sự.')}
async function toggleStudent(user:DirectoryUser){await run(`student:${user.id}`,()=>updateManagedUser(runtime(),user.id,{changeCode:false,code:user.code,fullName:user.fullName,role:user.role,classId:user.classId,active:!user.active}),user.active?'Đã khóa tài khoản.':'Đã khôi phục tài khoản.')}
async function resetPassword(user:DirectoryUser|{id:string;code:string}){const password=window.prompt(`Mật khẩu mới cho ${user.code}:`)?.trim();if(!password)return;await run(`password:${user.id}`,()=>resetManagedPassword(user.id,password),'Đã đặt lại mật khẩu.')}
function hardDeleteConfirmation(code:string,label:string){const confirmCode=window.prompt(`Xóa vĩnh viễn ${label}. Nhập mã ${code}:`)?.trim().toUpperCase();if(confirmCode!==code.toUpperCase())return null;const phrase=window.prompt('Thao tác không thể khôi phục. Nhập chính xác: XÓA VĨNH VIỄN')?.trim().toUpperCase();if(phrase!=='XÓA VĨNH VIỄN')return null;return{confirmCode,phrase}}
async function hardDeleteLearner(user:DirectoryUser){const confirmation=hardDeleteConfirmation(user.code,user.fullName||user.code);if(!confirmation)return;await run(`hard:${user.id}`,()=>hardDeleteUser(runtime(),user.id,confirmation.confirmCode,confirmation.phrase),'Đã xóa vĩnh viễn học sinh/cán sự.')}
async function submitTeacher(){const code=teacherForm.code.trim().toUpperCase(),fullName=teacherForm.fullName.trim();if(!code||!fullName)return;let result:unknown;await run('create-teacher',async()=>{result=await createTeacher(runtime(),{code,fullName,role:'teacher',classId:null,active:true,password:teacherForm.password})},'Đã tạo giáo viên.');const password=String((result as {password?:unknown}|undefined)?.password??'');if(password)statusMessage.value=`Đã tạo ${code}. Mật khẩu tạm: ${password}`;teacherForm.code='';teacherForm.fullName='';teacherForm.password='';showTeacherForm.value=false}
async function toggleTeacher(id:string){const teacher=data.value.teachers.find(row=>row.id===id);if(!teacher)return;await run(`teacher:${id}`,()=>updateTeacher(runtime(),id,{changeCode:false,code:teacher.code,fullName:teacher.fullName,role:'teacher',classId:null,active:!teacher.active}),teacher.active?'Đã khóa giáo viên.':'Đã mở khóa giáo viên.')}
async function editTeacher(id:string){const teacher=data.value.teachers.find(row=>row.id===id);if(!teacher)return;const code=window.prompt('Mã đăng nhập giáo viên:',teacher.code)?.trim().toUpperCase();if(!code)return;const fullName=window.prompt('Họ và tên giáo viên:',teacher.fullName)?.trim();if(!fullName)return;await run(`teacher:${id}`,()=>updateTeacher(runtime(),id,{changeCode:code!==teacher.code,code,fullName,role:'teacher',classId:null,active:teacher.active}),'Đã cập nhật giáo viên.')}
async function hardDeleteTeacher(id:string){const teacher=data.value.teachers.find(row=>row.id===id);if(!teacher)return;if(assignedClasses(id).length){status.value='error';statusMessage.value='Hãy gỡ toàn bộ phân công lớp trước khi xóa vĩnh viễn giáo viên.';return}const confirmation=hardDeleteConfirmation(teacher.code,teacher.fullName||teacher.code);if(!confirmation)return;await run(`hard:${id}`,()=>hardDeleteUser(runtime(),id,confirmation.confirmCode,confirmation.phrase),'Đã xóa vĩnh viễn giáo viên.')}
async function permission(payload:{classId:string;teacherId:string;enabled:boolean}){const key=`${payload.classId}:${payload.teacherId}`;await run(key,()=>assignTeacher(runtime(),payload.classId,payload.teacherId,payload.enabled),'Đã cập nhật phân quyền giáo viên.')}
</script>
<template>
  <div class="page-stack admin-page">
    <header class="admin-header"><div><span class="page-context"><ShieldCheck/>ROOT ADMIN · QUẢN TRỊ HỆ THỐNG</span><h1>{{ tab==='overview'?'Tổng quan hệ thống':tab==='years'?'Năm học':tab==='classes'?'Lớp học':tab==='students'?'Học sinh':tab==='teachers'?'Giáo viên':tab==='permissions'?'Phân quyền':'Nhật ký hệ thống' }}</h1><p>Admin quản lý cấu trúc, tài khoản và quyền hệ thống; nghiệp vụ vận hành lớp thuộc Giáo viên.</p></div><AppButton v-if="tab!=='audit'" variant="secondary" :loading="directory.isFetching.value" @click="directory.refetch()"><RefreshCw/>Làm mới</AppButton></header>
    <InlineStatus :state="status" :message="statusMessage"/>

    <template v-if="tab==='overview'">
      <section class="summary"><AppCard padding="lg"><span><CalendarDays/>Năm học</span><b>{{ schoolYearCount }}</b></AppCard><AppCard padding="lg"><span><Building2/>Lớp hoạt động</span><b>{{ activeClasses.length }}</b></AppCard><AppCard padding="lg"><span><GraduationCap/>HS/Cán sự hoạt động</span><b>{{ activeLearners.length }}</b></AppCard><AppCard padding="lg"><span><UserCog/>Giáo viên hoạt động</span><b>{{ activeTeachers.length }}</b></AppCard><AppCard padding="lg"><span><ShieldCheck/>Phân quyền</span><b>{{ activeAssignments.length }}</b></AppCard></section>
      <AppCard padding="lg" class="overview-copy"><h2>Ngữ cảnh hiện tại: {{ selectedYear?.name||'Chưa có năm học' }}</h2><p>Năm học quyết định danh sách lớp và lịch chuẩn. Các thao tác xóa vĩnh viễn đều được kiểm quyền ở backend và ghi vào Nhật ký hệ thống.</p></AppCard>
    </template>

    <template v-else-if="tab==='years'">
      <div class="section-actions"><div><h2>Năm học</h2><p>{{ schoolYearCount }} năm học. Chỉ một năm được đặt là đang hoạt động.</p></div><AppButton @click="showYearForm=!showYearForm"><Plus/>Tạo năm học</AppButton></div>
      <AppCard v-if="showYearForm" padding="md"><form class="quick-form year-form" @submit.prevent="submitYear"><label>Tên năm học<input v-model="yearForm.name" required maxlength="40" placeholder="2027–2028"></label><label>Ngày bắt đầu tuần 1<input v-model="yearForm.startDate" type="date" required></label><label>Ngày kết thúc năm học<input v-model="yearForm.endDate" type="date" required></label><label class="check-field"><input v-model="yearForm.setActive" type="checkbox">Đặt là năm học đang hoạt động</label><AppButton type="submit" :loading="busyKey==='create-year'">Tạo năm học</AppButton></form></AppCard>
      <section class="year-grid"><AdminSchoolYearCard v-for="item in mergedSchoolYears" :key="item.id" :item="item" :weeks="yearWeeks(item.id)" :periods="yearPeriods(item.id)" :busy="busyKey===`year:${item.id}`" :busy-week-id="busyKey?.startsWith('week:')?busyKey.slice(5):null" :busy-periods="busyKey===`periods:${item.id}`" @activate="activateYear" @save-week="saveYearWeek" @save-periods="saveYearPeriods"/></section>
    </template>

    <template v-else-if="tab==='classes'">
      <div class="section-actions"><div><h2>Lớp học · {{ selectedYear?.name||'—' }}</h2><p>{{ yearClasses.length }} lớp trong năm học đang chọn.</p></div><AppButton :disabled="!selectedYearId" @click="showClassForm=!showClassForm"><Plus/>Tạo lớp</AppButton></div>
      <AppCard v-if="showClassForm" padding="md"><form class="quick-form" @submit.prevent="submitClass"><label>Mã lớp<input v-model="classForm.code" required maxlength="40" placeholder="7A1"></label><label>Tên lớp<input v-model="classForm.name" required maxlength="120" placeholder="Lớp 7A1"></label><AppButton type="submit" :loading="busyKey==='create-class'">Tạo lớp</AppButton></form></AppCard>
      <section class="class-grid"><AdminClassCard v-for="item in yearClasses" :key="item.id" :item="item" :teachers="assignedTeachers(item.id)" @edit="editClass(item.id)" @toggle="toggleClass(item.id)" @delete="removeClass(item.id)"/></section>
    </template>

    <template v-else-if="tab==='students'">
      <div class="section-actions"><div><h2>Học sinh & Cán sự</h2><p>{{ learners.length }} tài khoản trên toàn hệ thống; có thể lọc theo năm học và lớp.</p></div><AppButton @click="showStudentForm=!showStudentForm"><Plus/>Tạo học sinh</AppButton></div>
      <AppCard v-if="showStudentForm" padding="md"><form class="student-form" @submit.prevent="submitStudent"><label>Mã đăng nhập<input v-model="studentForm.code" required></label><label>Họ và tên<input v-model="studentForm.fullName" required></label><label>Vai trò<select v-model="studentForm.role"><option value="student">Học sinh</option><option value="monitor">Cán sự</option></select></label><label>Lớp<select v-model="studentForm.classId" required><option value="">Chọn lớp</option><option v-for="item in data.classes.filter(x=>x.active)" :key="item.id" :value="item.id">{{ item.code }} · {{ mergedSchoolYears.find(y=>y.id===item.schoolYearId)?.name||'' }}</option></select></label><label>Mật khẩu tạm<input v-model="studentForm.password" type="password" placeholder="Để trống để tự sinh"></label><AppButton type="submit" :loading="busyKey==='create-student'">Tạo</AppButton></form></AppCard>
      <AppCard padding="md"><div class="student-filters"><input v-model="studentSearch" placeholder="Tìm tên, mã, lớp..."><select v-model="studentYearFilter"><option value="">Tất cả năm học</option><option v-for="year in mergedSchoolYears" :key="year.id" :value="year.id">{{ year.name }}</option></select><select v-model="studentClassFilter"><option value="">Tất cả lớp</option><option v-for="item in data.classes" :key="item.id" :value="item.id">{{ item.code }}</option></select><select v-model="studentRoleFilter"><option value="">HS + Cán sự</option><option value="student">Học sinh</option><option value="monitor">Cán sự</option></select><select v-model="studentStatusFilter"><option value="">Mọi trạng thái</option><option value="active">Hoạt động</option><option value="inactive">Đã khóa</option></select></div></AppCard>
      <section class="student-grid"><AdminStudentCard v-for="user in filteredLearners" :key="user.id" :user="user" :class-label="classById.get(user.classId||'')?.code||'Chưa có lớp'" @edit="editStudent(user)" @toggle="toggleStudent(user)" @reset="resetPassword(user)" @hard-delete="hardDeleteLearner(user)"/></section>
    </template>

    <template v-else-if="tab==='teachers'">
      <div class="section-actions"><div><h2>Giáo viên</h2><p>{{ data.teachers.length }} tài khoản. Muốn xóa vĩnh viễn phải gỡ hết phân công lớp trước.</p></div><AppButton @click="showTeacherForm=!showTeacherForm"><Plus/>Tạo giáo viên</AppButton></div>
      <AppCard v-if="showTeacherForm" padding="md"><form class="quick-form teacher-form" @submit.prevent="submitTeacher"><label>Mã đăng nhập<input v-model="teacherForm.code" required maxlength="32" placeholder="GV-HIEU"></label><label>Họ và tên<input v-model="teacherForm.fullName" required maxlength="120"></label><label>Mật khẩu tạm<input v-model="teacherForm.password" type="password" autocomplete="new-password" placeholder="Để trống để tự sinh"></label><AppButton type="submit" :loading="busyKey==='create-teacher'">Tạo giáo viên</AppButton></form></AppCard>
      <section class="teacher-grid"><AdminTeacherCard v-for="teacher in data.teachers" :key="teacher.id" :teacher="teacher" :classes="assignedClasses(teacher.id)" @edit="editTeacher(teacher.id)" @toggle="toggleTeacher(teacher.id)" @reset="resetPassword(teacher)" @hard-delete="hardDeleteTeacher(teacher.id)"/></section>
    </template>

    <template v-else-if="tab==='permissions'">
      <div class="section-actions"><div><h2>Phân quyền · {{ selectedYear?.name||'—' }}</h2><p>Bật/tắt quyền phụ trách từng lớp trong năm học đang chọn.</p></div></div><AppCard padding="lg"><PermissionMatrix :classes="activeClasses" :teachers="data.teachers" :assignments="data.assignments" :busy-key="busyKey" @change="permission"/></AppCard>
    </template>

    <AdminAuditLog v-else-if="tab==='audit'"/>
  </div>
</template>
<style scoped>
.admin-page{max-width:1560px;margin:0 auto}.admin-header,.section-actions{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.admin-header h1{margin:8px 0;font-size:clamp(2rem,4vw,3rem)}.admin-header p,.section-actions p,.overview-copy p{margin:0;color:var(--text-muted)}.page-context{display:flex;align-items:center;gap:7px;color:var(--color-primary);font-size:.75rem;font-weight:900;letter-spacing:.04em}.page-context svg,.admin-header :deep(svg),.section-actions :deep(svg){width:17px}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:11px}.summary :deep(.app-card){display:flex;align-items:center;justify-content:space-between}.summary span{display:flex;align-items:center;gap:7px;color:var(--text-muted);font-weight:800}.summary svg{width:18px}.summary b{font-size:1.8rem}.overview-copy h2,.section-actions h2{margin:0 0 5px}.year-grid{display:grid;grid-template-columns:1fr;gap:11px}.class-grid,.student-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.teacher-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:11px}.quick-form{display:grid;grid-template-columns:1fr 2fr auto;gap:10px;align-items:end}.quick-form.year-form{grid-template-columns:1.1fr 1fr 1fr 1.3fr auto}.quick-form.teacher-form{grid-template-columns:1fr 1.5fr 1.3fr auto}.student-form{display:grid;grid-template-columns:1fr 1.5fr .8fr 1.1fr 1.1fr auto;gap:9px;align-items:end}.quick-form label,.student-form label{display:grid;gap:5px;font-size:.78rem;font-weight:800;color:var(--text-muted)}.quick-form input,.student-form input,.student-form select,.student-filters input,.student-filters select{min-height:44px;border:1px solid var(--border);border-radius:11px;background:var(--surface);color:var(--text);padding:8px 10px}.quick-form .check-field{display:flex;align-items:center;gap:8px;min-height:44px;padding:8px 10px;border:1px solid var(--border);border-radius:11px;background:color-mix(in srgb,var(--wash-cream) 48%,var(--surface));color:var(--text)}.quick-form .check-field input{min-height:0;width:17px;height:17px}.student-filters{display:grid;grid-template-columns:minmax(220px,1.5fr) repeat(4,minmax(130px,.7fr));gap:8px}@media(max-width:1180px){.summary{grid-template-columns:repeat(3,1fr)}.quick-form.year-form,.student-form{grid-template-columns:1fr 1fr}.teacher-grid{grid-template-columns:repeat(2,1fr)}.quick-form,.quick-form.teacher-form{grid-template-columns:1fr 1fr}.quick-form :deep(.app-button),.student-form :deep(.app-button){width:100%}.student-filters{grid-template-columns:1fr 1fr}}@media(max-width:720px){.admin-header,.section-actions{flex-direction:column}.summary,.year-grid,.class-grid,.student-grid,.teacher-grid{grid-template-columns:1fr}.quick-form,.quick-form.year-form,.quick-form.teacher-form,.student-form,.student-filters{grid-template-columns:1fr}.admin-header :deep(.app-button),.section-actions :deep(.app-button){width:100%}}
</style>
