<script setup lang="ts">
import { computed } from 'vue'
import { AlertCircle, CheckCircle2, Laptop2, TriangleAlert, UsersRound } from 'lucide-vue-next'
import AppCard from '../components/ui/AppCard.vue'
import AppBadge from '../components/ui/AppBadge.vue'
import { useAuthStore } from '../stores/auth'
import { useContextStore } from '../stores/context'
import { useWeekData } from '../features/weeks/queries'
import { buildDashboardMetrics } from '../features/dashboard/dashboard-model'
import { useDailyQuote } from '../features/owl/daily-quote'
import { useNowTicker } from '../features/shared/useNowTicker'
const dashboardIllustrationUrl = `${import.meta.env.BASE_URL}assets/images/teacher-dashboard-illustration.png`
const auth=useAuthStore();const context=useContextStore();const nowMs=useNowTicker(30_000);const classId=computed(()=>context.selectedClassId);const weekId=computed(()=>context.selectedWeekId);const weekQuery=useWeekData(classId,weekId)
const slots=computed(()=>{const state=auth.legacyState;if(!state)return[];const overrides=(state.overrides??[]).filter(row=>row.weekId===weekId.value);return overrides.length?overrides.filter(row=>row.active!==false).map(row=>({dow:row.dow,period:row.period})):state.schedule??[]})
const registrations=computed(()=>weekQuery.data.value?.registrations??auth.legacyState?.registrations.filter(row=>row.weekId===weekId.value)??[])
const week=computed(()=>context.selectedWeek)
const metrics=computed(()=>buildDashboardMetrics({users:auth.legacyState?.users??[],registrations:registrations.value,slots:slots.value,week:week.value,periods:auth.legacyState?.periods??[],nowMs:nowMs.value}))
const dailyQuoteQuery=useDailyQuote();const dailyQuote=computed(()=>dailyQuoteQuery.data.value)
const isFetching=computed(()=>weekQuery.isFetching.value)
</script>
<template><div class="page-stack"><section class="welcome app-card"><div><AppBadge tone="primary">Tuần {{ week?.number??'–' }}</AppBadge><h1>Chào {{ auth.currentUser?.name||'bạn' }}</h1><p>{{ auth.legacyState?.settings.announcement||'Chuẩn bị nội dung tự học trước hạn.' }}</p><div class="week-meta" v-if="week">{{ week.startDate }} → {{ week.endDate }}</div></div><img :src="dashboardIllustrationUrl" alt=""/></section><section class="metrics"><AppCard><UsersRound/><b>{{ metrics.students }}</b><span>Học sinh</span></AppCard><AppCard><CheckCircle2/><b>{{ metrics.completion }}%</b><span>Đã đăng ký</span></AppCard><AppCard><AlertCircle/><b>{{ metrics.needsRevision }}</b><span>Cần chỉnh sửa</span></AppCard><AppCard><TriangleAlert/><b>{{ metrics.issues }}</b><span>Báo cáo lỗi</span></AppCard><AppCard><Laptop2/><b>{{ metrics.electronicDevices }}</b><span>Có thiết bị</span></AppCard></section><section class="daily-quote"><AppCard padding="lg"><span class="quote-kicker">Danh ngôn hôm nay</span><blockquote>“{{ dailyQuote?.text || 'Mỗi ngày học một điều mới là một bước tiến.' }}”</blockquote><cite>— {{ dailyQuote?.author || 'Cú Thông Thái' }}</cite></AppCard></section><section class="grid"><AppCard padding="lg"><div class="page-header"><div><h2>Tiến độ tuần</h2><p>Dữ liệu được quản lý bởi Vue Query, không render lại toàn ứng dụng.</p></div><AppBadge :tone="isFetching?'info':'success'">{{ isFetching?'Đang đồng bộ':'Đã đồng bộ' }}</AppBadge></div><div class="progress"><span :style="{width:`${metrics.completion}%`}"></span></div><div class="summary"><span>{{ metrics.submitted }}/{{ metrics.expected }} lượt đăng ký</span><span>{{ metrics.approved }} đã duyệt</span></div></AppCard><AppCard padding="lg"><h2>Cần chú ý</h2><p class="muted" v-if="metrics.needsRevision===0&&metrics.issues===0">Hiện chưa có đăng ký cần chú ý trong tuần đang xem.</p><p v-if="metrics.needsRevision"><b>{{ metrics.needsRevision }}</b> đăng ký đang cần học sinh chỉnh sửa.</p><p v-if="metrics.issues"><b>{{ metrics.issues }}</b> đăng ký đã chuyển sang Báo cáo lỗi.</p><RouterLink v-if="metrics.issues" class="issue-link" to="/issues">Xem Báo cáo lỗi →</RouterLink></AppCard></section></div></template>
<style scoped>
.welcome{display:grid;grid-template-columns:minmax(0,1fr) minmax(240px,390px);align-items:center;padding:30px;overflow:hidden;position:relative;background:radial-gradient(circle at 12% 18%,var(--wash-pink),transparent 34%),radial-gradient(circle at 82% 18%,var(--wash-sky),transparent 32%),linear-gradient(135deg,var(--wash-violet),color-mix(in srgb,var(--wash-mint) 38%,var(--surface)))}.welcome::after{content:"";position:absolute;right:-34px;bottom:-54px;width:190px;height:190px;border-radius:50%;background:color-mix(in srgb,var(--color-sun) 10%,transparent);pointer-events:none}.welcome>div,.welcome img{position:relative;z-index:1}.welcome h1{font-size:clamp(2rem,4vw,3.5rem);margin:10px 0 6px}.welcome p{color:var(--text-muted);max-width:58ch}.welcome img{justify-self:end;max-height:230px}.week-meta{display:inline-flex;margin-top:16px;padding:7px 10px;border-radius:999px;background:color-mix(in srgb,var(--surface) 70%,transparent);color:var(--text-muted);font-weight:800;border:1px solid color-mix(in srgb,var(--color-primary) 10%,var(--border))}
.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.metrics :deep(.card){--metric-accent:var(--color-primary);--metric-wash:var(--wash-violet);display:grid;grid-template-columns:auto 1fr;column-gap:12px;align-items:center;background:linear-gradient(145deg,var(--surface),var(--metric-wash));border-color:color-mix(in srgb,var(--metric-accent) 22%,var(--border))}.metrics :deep(.card:nth-child(1)){--metric-accent:var(--color-sky);--metric-wash:var(--wash-sky)}.metrics :deep(.card:nth-child(2)){--metric-accent:var(--color-mint);--metric-wash:var(--wash-mint)}.metrics :deep(.card:nth-child(3)){--metric-accent:var(--color-coral);--metric-wash:var(--wash-coral)}.metrics :deep(.card:nth-child(4)){--metric-accent:var(--color-sun);--metric-wash:var(--wash-sun)}.metrics :deep(.card:nth-child(5)){--metric-accent:var(--color-lilac);--metric-wash:var(--wash-violet)}.metrics :deep(svg){grid-row:1/3;width:30px;color:var(--metric-accent)}.metrics b{font-size:1.72rem;color:var(--text)}.metrics span{color:var(--text-muted);font-size:.84rem;font-weight:750}
.daily-quote :deep(.card){position:relative;overflow:hidden;background:linear-gradient(120deg,var(--wash-sky),var(--wash-violet) 46%,var(--wash-pink));border-color:color-mix(in srgb,var(--color-lilac) 20%,var(--border))}.daily-quote :deep(.card)::before{content:"✦";position:absolute;right:24px;top:12px;color:var(--color-sun);font-size:2rem;opacity:.65}.quote-kicker{color:var(--color-primary);font-size:.76rem;font-weight:900;letter-spacing:.08em}.daily-quote blockquote{margin:10px 0 6px;font-size:clamp(1rem,2vw,1.2rem);line-height:1.6;font-weight:800}.daily-quote cite{color:var(--text-muted);font-style:normal}
.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:18px}.grid :deep(.app-card:first-child){background:linear-gradient(145deg,var(--surface),color-mix(in srgb,var(--wash-sky) 60%,var(--surface)))}.grid :deep(.app-card:last-child){background:linear-gradient(145deg,var(--surface),color-mix(in srgb,var(--wash-sun) 70%,var(--surface)))}.grid h2{margin:0}.progress{height:13px;background:var(--surface-soft);border-radius:999px;overflow:hidden;margin:26px 0 10px}.progress span{display:block;height:100%;background:var(--gradient-celebrate);border-radius:inherit;transition:width .4s ease}.summary{display:flex;justify-content:space-between;gap:12px;color:var(--text-muted);font-size:.86rem;font-weight:700}.issue-link{display:inline-flex;margin-top:8px;color:var(--color-warning);font-weight:850;text-decoration:none}.issue-link:hover{text-decoration:underline}
@media(max-width:1100px){.metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.welcome{grid-template-columns:1fr}.welcome img{max-height:180px;justify-self:center}}@media(max-width:480px){.metrics{grid-template-columns:1fr}.welcome{padding:20px}}
</style>
