<script setup lang="ts">
import { computed } from 'vue'
import { AlertCircle, CheckCircle2, Laptop2, UsersRound } from 'lucide-vue-next'
import AppCard from '../components/ui/AppCard.vue'
import AppBadge from '../components/ui/AppBadge.vue'
import { useAuthStore } from '../stores/auth'
import { useContextStore } from '../stores/context'
import { useWeekData } from '../features/weeks/queries'
import { buildDashboardMetrics } from '../features/dashboard/dashboard-model'
import { useDailyQuote } from '../features/owl/daily-quote'
const dashboardIllustrationUrl = `${import.meta.env.BASE_URL}assets/images/teacher-dashboard-illustration.png`
const auth=useAuthStore();const context=useContextStore();const classId=computed(()=>context.selectedClassId);const weekId=computed(()=>context.selectedWeekId);const weekQuery=useWeekData(classId,weekId)
const slots=computed(()=>{const state=auth.legacyState;if(!state)return[];const overrides=(state.overrides??[]).filter(row=>row.weekId===weekId.value);return overrides.length?overrides.filter(row=>row.active!==false).map(row=>({dow:row.dow,period:row.period})):state.schedule??[]})
const registrations=computed(()=>weekQuery.data.value?.registrations??auth.legacyState?.registrations.filter(row=>row.weekId===weekId.value)??[])
const metrics=computed(()=>buildDashboardMetrics({users:auth.legacyState?.users??[],registrations:registrations.value,slots:slots.value}))
const dailyQuoteQuery=useDailyQuote();const dailyQuote=computed(()=>dailyQuoteQuery.data.value)
const isFetching=computed(()=>weekQuery.isFetching.value)
const week=computed(()=>context.selectedWeek)
</script>
<template><div class="page-stack"><section class="welcome app-card"><div><AppBadge tone="primary">Tuần {{ week?.number??'–' }}</AppBadge><h1>Chào {{ auth.currentUser?.name||'bạn' }}</h1><p>{{ auth.legacyState?.settings.announcement||'Chuẩn bị nội dung tự học trước hạn.' }}</p><div class="week-meta" v-if="week">{{ week.startDate }} → {{ week.endDate }}</div></div><img :src="dashboardIllustrationUrl" alt=""/></section><section class="metrics"><AppCard><UsersRound/><b>{{ metrics.students }}</b><span>Học sinh</span></AppCard><AppCard><CheckCircle2/><b>{{ metrics.completion }}%</b><span>Đã đăng ký</span></AppCard><AppCard><AlertCircle/><b>{{ metrics.needsRevision }}</b><span>Cần chỉnh sửa</span></AppCard><AppCard><Laptop2/><b>{{ metrics.electronicDevices }}</b><span>Có thiết bị</span></AppCard></section><section class="daily-quote"><AppCard padding="lg"><span class="quote-kicker">Danh ngôn hôm nay</span><blockquote>“{{ dailyQuote?.text || 'Mỗi ngày học một điều mới là một bước tiến.' }}”</blockquote><cite>— {{ dailyQuote?.author || 'Cú Thông Thái' }}</cite></AppCard></section><section class="grid"><AppCard padding="lg"><div class="page-header"><div><h2>Tiến độ tuần</h2><p>Dữ liệu được quản lý bởi Vue Query, không render lại toàn ứng dụng.</p></div><AppBadge :tone="isFetching?'info':'success'">{{ isFetching?'Đang đồng bộ':'Đã đồng bộ' }}</AppBadge></div><div class="progress"><span :style="{width:`${metrics.completion}%`}"></span></div><div class="summary"><span>{{ metrics.submitted }}/{{ metrics.expected }} lượt đăng ký</span><span>{{ metrics.approved }} đã duyệt</span></div></AppCard><AppCard padding="lg"><h2>Cần chú ý</h2><p class="muted" v-if="metrics.needsRevision===0">Hiện chưa có đăng ký cần chỉnh sửa trong tuần đang xem.</p><p v-else><b>{{ metrics.needsRevision }}</b> đăng ký đang cần học sinh chỉnh sửa.</p></AppCard></section></div></template>
<style scoped>.welcome{display:grid;grid-template-columns:minmax(0,1fr) minmax(240px,390px);align-items:center;padding:28px;overflow:hidden;background:linear-gradient(135deg,color-mix(in srgb,var(--color-primary) 12%,var(--surface)),var(--surface))}.welcome h1{font-size:clamp(2rem,4vw,3.5rem);margin:10px 0 6px}.welcome p{color:var(--text-muted);max-width:58ch}.welcome img{justify-self:end;max-height:230px}.week-meta{margin-top:16px;color:var(--text-muted);font-weight:700}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.metrics :deep(.card){display:grid;grid-template-columns:auto 1fr;column-gap:12px;align-items:center}.metrics :deep(svg){grid-row:1/3;width:28px;color:var(--color-primary)}.metrics b{font-size:1.65rem}.metrics span{color:var(--text-muted);font-size:.82rem}.daily-quote :deep(.card){background:linear-gradient(135deg,color-mix(in srgb,var(--color-info) 9%,var(--surface)),var(--surface))}.quote-kicker{color:var(--color-primary);font-size:.76rem;font-weight:850;letter-spacing:.08em}.daily-quote blockquote{margin:10px 0 6px;font-size:clamp(1rem,2vw,1.2rem);line-height:1.6;font-weight:750}.daily-quote cite{color:var(--text-muted);font-style:normal}.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:18px}.grid h2{margin:0}.progress{height:12px;background:var(--surface-soft);border-radius:999px;overflow:hidden;margin:26px 0 10px}.progress span{display:block;height:100%;background:linear-gradient(90deg,var(--color-primary),var(--color-info));border-radius:inherit;transition:width .4s ease}.summary{display:flex;justify-content:space-between;gap:12px;color:var(--text-muted);font-size:.86rem}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.welcome{grid-template-columns:1fr}.welcome img{max-height:180px;justify-self:center}}@media(max-width:480px){.metrics{grid-template-columns:1fr}.welcome{padding:20px}}</style>
