<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Bot, CheckCircle2, Clock3, Save, Sparkles } from 'lucide-vue-next'
import AppButton from '../components/ui/AppButton.vue'
import AppCard from '../components/ui/AppCard.vue'
import AppTabs from '../components/ui/AppTabs.vue'
import InlineStatus, { type InlineStatusState } from '../components/ui/InlineStatus.vue'
import { useAuthStore } from '../stores/auth'
import { useContextStore } from '../stores/context'
import { useLegacyMutationRuntime } from '../features/shared/useLegacyMutationRuntime'
import { saveSettingsMutation } from '../features/settings/settings-mutations'

const auth=useAuthStore(),context=useContextStore(),createRuntime=useLegacyMutationRuntime()
const activeTab=ref('general'),saving=ref(false),status=ref<InlineStatusState>('idle'),statusMessage=ref('')
const tabs=[{id:'general',label:'Chung & đăng ký'},{id:'ai',label:'AI duyệt'},{id:'owl',label:'Cú Thông Thái'}]
const announcement=ref(''),registrationDeadlineTime=ref('20:00'),aiAutoApproveThreshold=ref(90),smartApprovalEnabled=ref(true)
const settings=computed(()=>auth.legacyState?.settings??{})
const memory=computed<Record<string,unknown>>(()=>((auth.legacyState?.aiFeedbackMemoryStats as Record<string,unknown>|undefined)??{}))
const revisionThreshold=computed(()=>Math.round(Number(settings.value.aiRevisionActionThreshold??.85)*100))
function hydrate(){announcement.value=String(settings.value.announcement??'');registrationDeadlineTime.value=String(settings.value.registrationDeadlineTime??'20:00');aiAutoApproveThreshold.value=Math.round(Number(settings.value.aiAutoApproveThreshold??.9)*100);smartApprovalEnabled.value=Boolean(settings.value.aiAutomationEnabled??settings.value.smartApprovalEnabled??settings.value.aiReviewEnabled??true)}
watch(settings,hydrate,{immediate:true})
async function save(){if(!context.selectedClassId)return;saving.value=true;status.value='idle';try{await saveSettingsMutation(createRuntime(),context.selectedClassId,{announcement:announcement.value,registrationDeadlineTime:registrationDeadlineTime.value,aiAutomationEnabled:smartApprovalEnabled.value,aiAutoApproveThreshold:aiAutoApproveThreshold.value/100});status.value='success';statusMessage.value=`Đã lưu cài đặt. Deadline tự động: ${registrationDeadlineTime.value}.`}catch(error){status.value='error';statusMessage.value=error instanceof Error?error.message:'Không lưu được cài đặt.'}finally{saving.value=false}}
</script>
<template><div class="page-stack settings-page"><header><span>CẤU HÌNH ỨNG DỤNG</span><h1>Cài đặt</h1><p>Cấu hình lớp học, đăng ký, AI và trải nghiệm Cú Thông Thái.</p></header><AppTabs v-model="activeTab" :items="tabs" label="Nhóm cài đặt"/><InlineStatus :state="status" :message="statusMessage"/>
<form @submit.prevent="save"><AppCard v-if="activeTab==='general'" padding="lg" class="settings-card"><div class="section-title"><Clock3/><div><span>THÔNG TIN LỚP</span><h2>Thiết lập chung</h2></div></div><div class="field-grid"><label>Tên lớp<input :value="String(settings.className??context.selectedClass?.name??'')" readonly></label><label>Năm học<input :value="String(settings.schoolYear??'')" readonly></label><label>Mốc deadline tự động<input v-model="registrationDeadlineTime" type="time" step="60"><small>Áp dụng cho chế độ “tối hôm trước từng buổi”.</small></label><label class="wide">Thông báo tuần<textarea v-model="announcement" rows="4"/></label></div><div class="periods"><span v-for="period in auth.legacyState?.periods??[]" :key="period.n"><b>Tiết {{ period.n }}</b><small>{{ period.start }} – {{ period.end }}</small></span></div></AppCard>
<AppCard v-else-if="activeTab==='ai'" padding="lg" class="settings-card"><div class="section-title"><Bot/><div><span>TỰ ĐỘNG HÓA</span><h2>Duyệt đăng ký bằng AI</h2></div></div><label class="toggle"><input v-model="smartApprovalEnabled" type="checkbox"><span><b>Duyệt tự động bằng AI</b><small><strong>Bật:</strong> Groq kiểm tra đăng ký mới/gửi lại và học từ phản hồi GV.</small><small><strong>Tắt:</strong> Mọi đăng ký chuyển GV duyệt.</small></span></label><div class="threshold"><div><b>Ngưỡng AI được tự duyệt</b><small>AI dưới ngưỡng này luôn chuyển GV.</small></div><strong>{{ aiAutoApproveThreshold }}%</strong><input v-model.number="aiAutoApproveThreshold" type="range" min="80" max="99" step="1"></div><p class="explain">Đăng ký mới dùng ngưỡng <b>{{ aiAutoApproveThreshold }}%</b>. Khi học sinh sửa theo phản hồi GV, AI chỉ tự hành động khi độ chắc chắn đạt <b>{{ revisionThreshold }}%</b>; trường hợp không chắc chuyển giáo viên.</p><div class="memory"><span><small>Phản hồi đã ghi nhận</small><b>{{ Number(memory.totalFeedback??0) }}</b></span><span><small>AI duyệt → GV yêu cầu sửa</small><b>{{ Number(memory.revisionAfterAiApprove??0) }}</b></span><span><small>AI chuyển GV → GV duyệt</small><b>{{ Number(memory.approveAfterAiManual??0) }}</b></span><span><small>AI yêu cầu sửa → GV duyệt</small><b>{{ Number(memory.approveAfterAiRevision??0) }}</b></span></div></AppCard>
<AppCard v-else padding="lg" class="settings-card owl-settings"><div class="section-title"><Sparkles/><div><span>TRỢ LÝ TRONG APP</span><h2>Cú Thông Thái</h2></div></div><p>Cú đọc ngữ cảnh trang/lớp/tuần, ưu tiên cảnh báo và luân phiên danh ngôn khi người dùng tương tác.</p><div class="feature-list"><span><CheckCircle2/>Mắt chuyển động nhẹ và đầu nghiêng theo con trỏ.</span><span><CheckCircle2/>Dữ liệu trang hiện tại được ưu tiên trước nội dung chung.</span><span><CheckCircle2/>Danh ngôn hôm nay ổn định theo ngày; các câu của Cú được luân phiên để tránh lặp.</span></div></AppCard>
<div class="save-bar"><span>Mọi thay đổi chỉ được lưu khi bấm nút bên cạnh.</span><AppButton type="submit" :loading="saving"><Save/>Lưu cài đặt</AppButton></div></form></div></template>
<style scoped>.settings-page{max-width:1200px;margin:0 auto}.settings-page>header span,.section-title span{color:var(--color-primary);font-size:.78rem;font-weight:850;letter-spacing:.08em}.settings-page>header h1{margin:7px 0;font-size:clamp(2rem,4vw,3rem)}.settings-page>header p{color:var(--text-muted)}form{display:grid;gap:16px}.section-title{display:flex;gap:12px;align-items:center;margin-bottom:20px}.section-title>svg{width:28px;color:var(--color-primary)}.section-title h2{margin:4px 0}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field-grid label{display:grid;gap:7px;font-weight:750}.field-grid input,.field-grid textarea{width:100%;border:1px solid var(--border);border-radius:12px;padding:11px 12px;background:var(--surface);color:var(--text);font:inherit}.field-grid input:focus,.field-grid textarea:focus{outline:3px solid var(--focus-ring);border-color:var(--color-primary)}.field-grid small{color:var(--text-muted);font-weight:500}.wide{grid-column:1/-1}.periods,.memory{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:18px}.periods span,.memory span{display:grid;gap:3px;padding:12px;border-radius:12px;background:var(--surface-soft)}.periods small,.memory small,.threshold small{color:var(--text-muted)}.toggle{display:flex;align-items:flex-start;gap:12px;padding:14px;border:1px solid var(--border);border-radius:14px}.toggle>input{margin-top:4px}.toggle>span{display:grid;gap:6px}.toggle small{display:block;margin-left:18px;color:var(--text-muted);line-height:1.5}.threshold{display:grid;grid-template-columns:1fr auto;gap:10px;margin-top:18px;padding:16px;border-radius:14px;background:var(--surface-soft)}.threshold>div{display:grid}.threshold>strong{font-size:1.3rem;color:var(--color-primary)}.threshold input{grid-column:1/-1;width:100%}.explain{color:var(--text-muted);line-height:1.6}.feature-list{display:grid;gap:10px}.feature-list span{display:flex;align-items:center;gap:9px}.feature-list svg{width:19px;color:var(--color-success)}.owl-settings>p{color:var(--text-muted)}.save-bar{position:sticky;bottom:12px;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 14px;border:1px solid var(--border);border-radius:14px;background:color-mix(in srgb,var(--surface) 92%,transparent);backdrop-filter:blur(10px);box-shadow:var(--shadow-md)}.save-bar>span{color:var(--text-muted);font-size:.85rem}.save-bar svg{width:18px}@media(max-width:800px){.field-grid{grid-template-columns:1fr}.wide{grid-column:auto}.periods,.memory{grid-template-columns:repeat(2,1fr)}}@media(max-width:540px){.periods,.memory{grid-template-columns:1fr}.save-bar{align-items:stretch;flex-direction:column}.save-bar :deep(button){width:100%}}
</style>
