import {chromium,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';
import {startPreview} from './preview-server.mjs';
const evidence=new URL('../../docs/feat-005/evidence/',import.meta.url);await mkdir(evidence,{recursive:true});
const fixture=await startPreview();let browser;const errors=[];const events=[];
try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:1000}});
 context.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});});
 async function pageFor(role){const p=await context.newPage();await p.goto('http://127.0.0.1:4175/tests/feat-005/preview.html?role='+role);await expect(p.getByRole('heading',{name:'Báo bài',exact:true})).toBeVisible();await expect(p.getByRole('heading',{name:'Bài tập',exact:true})).toBeVisible();return p;}
 const monitor=await pageFor('monitor');
 await expect(monitor.getByRole('button',{name:'Sửa',exact:true})).toHaveCount(0);await expect(monitor.getByRole('button',{name:'🔔 Nhắc',exact:true})).toHaveCount(0);
 await monitor.getByRole('button',{name:'Báo sai thông tin',exact:true}).click();
 const report=monitor.getByRole('dialog');await expect(report).toBeVisible();await report.getByLabel('Ghi chú (không bắt buộc)').fill('PRIVATE_REPORT_BROWSER');await report.getByRole('button',{name:'Báo sai thông tin',exact:true}).click();await expect(report).toHaveCount(0);events.push('Monitor report submitted; edit/delete/remind absent.');
 const teacher=await pageFor('teacher');await teacher.getByRole('button',{name:'Báo sai thông tin',exact:true}).click();await expect(teacher.getByText('PRIVATE_REPORT_BROWSER',{exact:true})).toBeVisible();await teacher.getByRole('button',{name:'Hợp lệ',exact:true}).click();await expect(teacher.getByText('Chờ xử lý',{exact:false})).toHaveCount(0);
 await teacher.screenshot({path:fileURLToPath(new URL('teacher-reports.png',evidence)),fullPage:true});
 await teacher.getByRole('button',{name:'Bảng Báo bài',exact:true}).click();await expect(teacher.getByRole('button',{name:'Sửa',exact:true})).toHaveCount(0);
 await teacher.getByRole('button',{name:'Yêu cầu chỉnh sửa Báo bài',exact:true}).click();const request=teacher.getByRole('dialog');await request.getByLabel('Lý do / hướng dẫn bắt buộc').fill('Sửa bài tập theo hướng dẫn');await request.getByRole('button',{name:'Yêu cầu chỉnh sửa Báo bài',exact:true}).click();await expect(request).toHaveCount(0);events.push('Assigned Teacher sees report and requests correction.');
 const author=await pageFor('student');await expect(author.getByText('PRIVATE_REPORT_BROWSER')).toHaveCount(0);await expect(author.getByRole('button',{name:'Báo sai thông tin',exact:true})).toHaveCount(0);await expect(author.getByRole('button',{name:'Xóa',exact:true})).toHaveCount(0);
 await author.getByRole('button',{name:'Sửa',exact:true}).click();let editor=author.getByRole('dialog');await editor.getByLabel('Nội dung',{exact:true}).fill('PRIVATE_BROWSER_REVISION');await editor.getByRole('button',{name:'Lưu bản nháp',exact:true}).click();await expect(author.getByText('Đã lưu bản nháp riêng tư',{exact:false})).toBeVisible();
 await monitor.getByRole('button',{name:'↻ Làm mới'}).click();await expect(monitor.getByText('PRIVATE_BROWSER_REVISION')).toHaveCount(0);await expect(monitor.getByText('Trang 10 bài 1',{exact:true})).toBeVisible();
 await editor.getByRole('button',{name:'Gửi lại GV',exact:true}).click();await expect(editor).toHaveCount(0);await expect(author.getByText('Đồng hồ đã dừng',{exact:false})).toBeVisible();events.push('Private draft saved; published board unchanged; author resubmission stops timer.');
 await teacher.getByRole('button',{name:'↻ Làm mới'}).click();await teacher.getByRole('button',{name:'Yêu cầu chỉnh sửa',exact:true}).click();await teacher.getByLabel('Lý do nếu chưa đạt').fill('Cần thêm nội dung');await teacher.getByRole('button',{name:'Chưa đạt — mở vòng 2',exact:true}).click();await expect(teacher.getByText('Lần chỉnh sửa cuối',{exact:false}).first()).toBeVisible();
 await author.getByRole('button',{name:'↻ Làm mới'}).click();await expect(author.getByText('Lần chỉnh sửa cuối',{exact:false}).first()).toBeVisible();await author.getByRole('button',{name:'Sửa và gửi lại GV',exact:true}).click();editor=author.getByRole('dialog');await editor.getByLabel('Nội dung',{exact:true}).fill('Bài tập đã chỉnh sửa hoàn chỉnh');await editor.getByRole('button',{name:'Gửi lại GV',exact:true}).click();await expect(editor).toHaveCount(0);
 await teacher.getByRole('button',{name:'↻ Làm mới'}).click();await teacher.getByRole('button',{name:'Đạt',exact:true}).click();await expect(teacher.getByText('Đã xác nhận và công bố chỉnh sửa.',{exact:true})).toBeVisible();await monitor.getByRole('button',{name:'↻ Làm mới'}).click();await expect(monitor.getByText('Bài tập đã chỉnh sửa hoàn chỉnh',{exact:true})).toBeVisible();events.push('Round 2 final warning; Teacher approval runs actual duplicate logic with local deterministic AI provider.');
 await author.getByRole('button',{name:'↻ Làm mới'}).click();await author.setViewportSize({width:390,height:844});await author.screenshot({path:fileURLToPath(new URL('author-correction-mobile.png',evidence)),fullPage:true});
 const overflow=await author.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);expect(overflow).toBe(false);
 await teacher.screenshot({path:fileURLToPath(new URL('teacher-correction-desktop.png',evidence)),fullPage:true});
 await teacher.getByRole('button',{name:'Bảng Báo bài',exact:true}).click();await teacher.getByRole('button',{name:'Gỡ bài',exact:true}).click();const emergency=teacher.getByRole('dialog');await emergency.getByLabel('Lý do / hướng dẫn bắt buộc').fill('Kiểm tra gỡ bài khẩn cấp');await emergency.getByRole('button',{name:'Gỡ bài khẩn cấp',exact:true}).click();await expect(emergency).toHaveCount(0);await monitor.getByRole('button',{name:'↻ Làm mới'}).click();await expect(monitor.getByRole('heading',{name:'Bài tập',exact:true})).toHaveCount(0);events.push('Emergency removal hides notice from board.');
 const admin=await context.newPage();await admin.goto('http://127.0.0.1:4175/tests/feat-005/preview.html?role=admin');await admin.getByRole('button',{name:'Thùng rác',exact:true}).click();await expect(admin.getByText('Người gỡ:',{exact:false})).toBeVisible();await expect(admin.getByRole('button',{name:'Yêu cầu chỉnh sửa',exact:true})).toHaveCount(0);await expect(admin.getByRole('button',{name:'Báo sai thông tin',exact:true})).toHaveCount(0);events.push('Admin Trash attribution visible; daily moderation actions absent.');
 expect(errors).toEqual([]);events.push('No browser console/page errors; 390px width has no horizontal overflow.');
 await writeFile(new URL('browser.json',evidence),JSON.stringify({status:'PASS',executedAt:new Date().toISOString(),environment:'Headless Chrome + real Vue page + PGlite 05–09; deterministic local AI; no live Auth/Edge deployment',events,errors},null,2));console.log('Browser PASS: '+events.length+' checks');
}catch(e){await writeFile(new URL('browser.json',evidence),JSON.stringify({status:'FAIL',events,errors,error:e.stack},null,2));throw e;}
finally{await browser?.close();await fixture.close();}
